## Escrever objetivo da análise

## Código

In [220]:
## Imports
import os
import pandas as pd
from pathlib import Path
from IPython.display import display
from bs4 import BeautifulSoup

In [221]:
# Leitura do arquivo CSV

BASE_PATH = "../../Takeout/YouTube e YouTube Music"
os.listdir(BASE_PATH)

['canais',
 'chats ao vivo',
 'comentários',
 'histórico',
 'inscrições',
 'playlists']

In [222]:
def ler_e_exibir_csvs_canais():
    # caminho base usando mesmo padrão que funciona acima
    base_dir = Path("../../Takeout/YouTube e YouTube Music/canais")
    
    # pega todos os csv da pasta
    arquivos_csv = list(base_dir.glob("*.csv"))
    
    print(f"Total de arquivos CSV encontrados: {len(arquivos_csv)}\n")
    
    for arquivo in arquivos_csv:
        print(f"\nArquivo: {arquivo.name}")
        
        df = pd.read_csv(arquivo)

        print("\n--- dtypes antes de convert_dtypes() ---")
        display(df.dtypes)

        # converter para os dtypes recomendados (string, Int64, etc.)
        df = df.convert_dtypes()

        print("\n--- dtypes após convert_dtypes() ---")
        display(df.dtypes)

        print("\n--- Visualização dos dados (primeiras linhas) ---")
        display(df.head())

In [223]:
ler_e_exibir_csvs_canais()

Total de arquivos CSV encontrados: 5


Arquivo: canal.csv

--- dtypes antes de convert_dtypes() ---

ID do canal                   object
Título do canal (Original)    object
Visibilidade do canal         object
dtype: object

--- dtypes após convert_dtypes() ---

ID do canal                   string[python]
Título do canal (Original)    string[python]
Visibilidade do canal         string[python]
dtype: object

--- Visualização dos dados (primeiras linhas) ---

                ID do canal Título do canal (Original) Visibilidade do canal
0  UC0hkw9AMjAfo0y78nTuRWfA        Giovanna Nascimento               Público

Arquivo: configurações da página do canal.csv

--- dtypes antes de convert_dtypes() ---

ID do canal    object
dtype: object

--- dtypes após convert_dtypes() ---

ID do canal    string[python]
dtype: object

--- Visualização dos dados (primeiras linhas) ---

                ID do canal
0  UC0hkw9AMjAfo0y78nTuRWfA

Arquivo: configurações de moderação da comunidade do can.csv

--- dtypes antes de convert_dtypes() ---

ID do canal    object
dtype: object

--- dtypes após convert_dtypes() ---

ID do canal    string[python]
dtype: object

--- Visualização dos dados (primeiras linhas) ---

                ID do canal
0  UC0hkw9AMjAfo0y78nTuRWfA

Arquivo: configurações de URL do canal.csv

--- dtypes antes de convert_dtypes() ---

ID do canal                     object
Nome do URL curto 1 do canal    object
dtype: object

--- dtypes após convert_dtypes() ---

ID do canal                     string[python]
Nome do URL curto 1 do canal    string[python]
dtype: object

--- Visualização dos dados (primeiras linhas) ---

                ID do canal Nome do URL curto 1 do canal
0  UC0hkw9AMjAfo0y78nTuRWfA       giovannanascimento-q9c

Arquivo: dados de recursos do canal.csv

--- dtypes antes de convert_dtypes() ---

ID do canal                                       object
Moderação automática do canal no chat ao vivo     object
Tipo de comentários permitidos padrão do vídeo    object
Público-alvo padrão do vídeo                      object
Licença padrão do vídeo                           object
Latitude do local padrão do vídeo                  int64
Longitude do local padrão do vídeo                 int64
dtype: object

--- dtypes após convert_dtypes() ---

ID do canal                                       string[python]
Moderação automática do canal no chat ao vivo     string[python]
Tipo de comentários permitidos padrão do vídeo    string[python]
Público-alvo padrão do vídeo                      string[python]
Licença padrão do vídeo                           string[python]
Latitude do local padrão do vídeo                          Int64
Longitude do local padrão do vídeo                         Int64
dtype: object

--- Visualização dos dados (primeiras linhas) ---

,ID do canal,Moderação automática do canal no chat ao vivo,Tipo de comentários permitidos padrão do vídeo,Público-alvo padrão do vídeo,Licença padrão do vídeo,Latitude do local padrão do vídeo,Longitude do local padrão do vídeo
0,UC0hkw9AMjAfo0y78nTuRWfA,falso,Não definido,Não definido,Não definido,0,0

<div style="border: 2px solid #c77dff ; padding: 18px; border-radius: 12px; background-color: #f8f0;">

<h2 style="color:#7b2cbf;"> 📺 Explicação das Colunas dos Arquivos CSV</h2>

---

<h3 style="color:#9d4edd;"> canal.csv</h3>

| Coluna | Tipo | Explicação |
|--------|------|------------|
| ID do canal | object (str) | Identificador único do canal dentro do YouTube. Funciona como chave de ligação entre todos os outros arquivos. |
| Título do canal (Original) | object (str) | Nome oficial exibido publicamente no canal. |
| Visibilidade do canal | object (str) | Define se o canal está público, privado ou restrito. |

---

<h3 style="color:#9d4edd;"> configurações da página do canal.csv</h3>

| Coluna | Tipo | Explicação |
|--------|------|------------|
| ID do canal | object (str) | Referência ao canal ao qual as configurações da página principal pertencem. |

---

<h3 style="color:#9d4edd;"> configurações de moderação da comunidade do can.csv</h3>

| Coluna | Tipo | Explicação |
|--------|------|------------|
| ID do canal | object (str) | Identifica qual canal possui aquelas regras de moderação da comunidade (comentários, chat, interações). |

---

<h3 style="color:#9d4edd;"> configurações de URL do canal.csv</h3>

| Coluna | Tipo | Explicação |
|--------|------|------------|
| ID do canal | object (str) | Identificador do canal. |
| Nome do URL curto 1 do canal | object (str) | Nome personalizado usado para gerar o link curto do canal (ex: youtube.com/@nome). |

---

<h3 style="color:#9d4edd;"> dados de recursos do canal.csv</h3>

| Coluna | Tipo | Explicação |
|--------|------|------------|
| ID do canal | object (str) | Identificador do canal. |
| Moderação automática do canal no chat ao vivo | object (str) | Indica se o YouTube aplica filtros automáticos no chat de transmissões ao vivo. |
| Tipo de comentários permitidos padrão do vídeo | object (str) | Configuração padrão de comentários aplicada aos vídeos. |
| Público-alvo padrão do vídeo | object (str) | Define se o conteúdo é voltado para crianças, adultos ou não definido. |
| Licença padrão do vídeo | object (str) | Tipo de licença aplicada automaticamente aos vídeos publicados. |
| Latitude do local padrão do vídeo | int64 | Coordenada geográfica padrão associada aos vídeos. |
| Longitude do local padrão do vídeo | int64 | Coordenada geográfica padrão associada aos vídeos. |

---

<h3 style="color:#9d4edd;"> imagens do canal.csv</h3>

| Coluna | Tipo | Explicação |
|--------|------|------------|
| Criar Carimbo de data/hora | object (str) | Momento exato em que a imagem do canal foi registrada ou atualizada na plataforma. |
| URL de conteúdo completo da imagem do canal | object (str) | Endereço onde a imagem de perfil do canal está armazenada nos servidores do YouTube. |

</div>

----

In [224]:
def ler_e_exibir_csvs_chats_ao_vivo():
    # caminho base usando mesmo padrão que funciona acima
    base_dir = Path("../../Takeout/YouTube e YouTube Music/chats ao vivo")
    
    # pega todos os csv da pasta
    arquivos_csv = list(base_dir.glob("*.csv"))
    
    print(f"Total de arquivos CSV encontrados: {len(arquivos_csv)}\n")
    
    for arquivo in arquivos_csv:
        print(f"\nArquivo: {arquivo.name}")
        
        df = pd.read_csv(arquivo)

        print("\n--- dtypes antes de convert_dtypes() ---")
        display(df.dtypes)

        df = df.convert_dtypes()

        print("\n--- dtypes após convert_dtypes() ---")
        display(df.dtypes)

        print("\n--- Visualização dos dados (primeiras linhas) ---")
        display(df.head())

In [225]:
ler_e_exibir_csvs_chats_ao_vivo()

Total de arquivos CSV encontrados: 1


Arquivo: chats ao vivo.csv

--- dtypes antes de convert_dtypes() ---

ID do chat ao vivo                              object
ID do canal                                     object
Marcação de tempo da criação do chat ao vivo    object
Preço                                            int64
ID do vídeo                                     object
Texto do chat ao vivo                           object
dtype: object

--- dtypes após convert_dtypes() ---

ID do chat ao vivo                              string[python]
ID do canal                                     string[python]
Marcação de tempo da criação do chat ao vivo    string[python]
Preço                                                    Int64
ID do vídeo                                     string[python]
Texto do chat ao vivo                           string[python]
dtype: object

--- Visualização dos dados (primeiras linhas) ---

,ID do chat ao vivo,ID do canal,Marcação de tempo da criação do chat ao vivo,Preço,ID do vídeo,Texto do chat ao vivo
0,Ugxg_lF0waCeqts5U1R4AaABDqgB-7OWnAI,UC0hkw9AMjAfo0y78nTuRWfA,2026-01-12T23:00:40.906546+00:00,0,OGrp5L0KFe4,"{""text"":""simm""}"
1,UgyvDlIcAtRKtN7m1Mx4AaABDqgB9_S7gwI,UC0hkw9AMjAfo0y78nTuRWfA,2026-01-12T22:56:22.036385+00:00,0,OGrp5L0KFe4,"{""text"":""trellooo""}"
2,UgzpF_SEeZsCLFTEaZV4AaABDqgBvP68mAI,UC0hkw9AMjAfo0y78nTuRWfA,2026-01-12T22:54:38.819714+00:00,0,OGrp5L0KFe4,"{""text"":""7""}"
3,Ugw3i5gYGPjAfb-kPJJ4AaABDqgBurnMjAI,UC0hkw9AMjAfo0y78nTuRWfA,2026-01-12T22:20:20.094369+00:00,0,OGrp5L0KFe4,"{""text"":""euuu""}"
4,UgxnPK1B6cQEJ6w-l-Z4AaABDqgBgsutmQI,UC0hkw9AMjAfo0y78nTuRWfA,2026-01-12T22:12:02.666665+00:00,0,OGrp5L0KFe4,"{""text"":""Class of 2026""}"

<div style="border: 2px solid #c77dff; padding: 18px; border-radius: 12px; background-color: #f8f0;">

<h2 style="color:#7b2cbf;">🎙️ Chats ao vivo.csv — Explicação das Colunas</h2>

<p>Este arquivo registra as mensagens enviadas em <b>chats ao vivo</b> durante transmissões do YouTube.  
Ele mostra que o YouTube armazena não apenas os vídeos, mas também <b>todas as interações textuais realizadas em lives</b>, associando cada mensagem ao canal, ao vídeo e ao momento exato do envio.</p>

---

<h3 style="color:#9d4edd;">📋 Chats ao vivo.csv</h3>

| Coluna | Tipo | Explicação |
|--------|------|------------|
| ID do chat ao vivo | object (str) | Identificador único de cada mensagem enviada no chat durante a live. |
| ID do canal | object (str) | Identifica qual canal estava realizando a transmissão ao vivo. |
| Marcação de tempo da criação do chat ao vivo | object (str) | Data e hora exata (timestamp) em que a mensagem foi enviada no chat. |
| Preço | int64 | Indica se a mensagem foi enviada como Super Chat (pago). Valor 0 significa que não houve pagamento. |
| ID do vídeo | object (str) | Identificador do vídeo (live) onde o chat ocorreu. Permite relacionar a mensagem à transmissão específica. |
| Texto do chat ao vivo | object (str) | Conteúdo textual da mensagem enviada no chat, armazenado em formato estruturado (JSON). |

---

<p>
Essas informações mostram que o YouTube mantém um <b>registro detalhado das interações em tempo real</b> realizadas pelos usuários durante transmissões ao vivo, incluindo o conteúdo da mensagem e o contexto em que ela foi enviada.
</p>

</div>

In [226]:
def ler_e_exibir_html_historico():
    base_dir = Path("../../Takeout/YouTube e YouTube Music/histórico")
    arquivos_html = list(base_dir.glob("*.html"))

    print(f"Total de arquivos HTML encontrados: {len(arquivos_html)}\n")

    for arquivo in arquivos_html:
        print(f"\nArquivo: {arquivo.name}")

        with open(arquivo, "r", encoding="utf-8") as f:
            soup = BeautifulSoup(f, "html.parser")

        dados = []

        blocos = soup.find_all(
            "div",
            class_="content-cell mdl-cell mdl-cell--6-col mdl-typography--body-1"
        )

        for bloco in blocos:
            link = bloco.find("a")
            if not link:
                continue

            # termo pesquisado
            titulo = link.text.strip()
            url = link["href"]

            # texto completo do bloco
            texto = bloco.get_text(separator=" ", strip=True)

            # tipo da ação (antes do link)
            tipo = texto.split(titulo)[0].strip()

            # data (depois do link)
            data = texto.split(titulo)[-1].strip()

            dados.append([tipo, titulo, url, data])

        df = pd.DataFrame(dados, columns=["tipo", "titulo", "url", "data"])

        print("\n--- dtypes antes de convert_dtypes() ---")
        display(df.dtypes)

        df = df.convert_dtypes()

        print("\n--- dtypes após convert_dtypes() ---")
        display(df.dtypes)

        print(f"\n📊 Dados (primeiras 20 linhas):")
        display(df.head(20))

In [227]:
ler_e_exibir_html_historico()

Total de arquivos HTML encontrados: 2


Arquivo: histórico de pesquisa.html

--- dtypes antes de convert_dtypes() ---

tipo      object
titulo    object
url       object
data      object
dtype: object

--- dtypes após convert_dtypes() ---

tipo      string[python]
titulo    string[python]
url       string[python]
data      string[python]
dtype: object

📊 Dados (primeiras 20 linhas):

,tipo,titulo,url,data
0,Watched,Mycon | Como todo consórcio deveria ser (16x9),https://www.youtube.com/watch?v=EPuSc-G3v9A,"Watched at 12:34 7 de fev. de 2026, 12:34:54 BRT"
1,Searched for,cristo jesus,https://www.youtube.com/results?search_query=c...,"7 de fev. de 2026, 12:32:56 BRT"
2,Watched,Jornada Python - ADV LPY25 04h sem data Newton,https://www.youtube.com/watch?v=r4dbQy7IHE8,"Watched at 12:31 7 de fev. de 2026, 12:31:43 BRT"
3,Watched,CAGE0230.Google.PWA.Contentformance_3mil.Calcu...,https://www.youtube.com/watch?v=n1arSFa2gds,"Watched at 11:35 7 de fev. de 2026, 11:35:21 BRT"
4,Watched,Linha Can-Am 2026: Defender,https://www.youtube.com/watch?v=ByQeHi42Upw,"Watched at 11:29 7 de fev. de 2026, 11:29:42 BRT"
5,Watched,Easy Because ClickUp (PT-BR),https://www.youtube.com/watch?v=cWrNNL6Fje4,"Watched at 11:18 7 de fev. de 2026, 11:18:23 BRT"
6,Searched for,grande é o senhor davi silva,https://www.youtube.com/results?search_query=g...,"7 de fev. de 2026, 11:18:21 BRT"
7,Searched for,grande é o senhor,https://www.youtube.com/results?search_query=g...,"7 de fev. de 2026, 11:15:16 BRT"
8,Watched,Easy Because ClickUp (PT-BR),https://www.youtube.com/watch?v=cWrNNL6Fje4,"Watched at 07:42 4 de fev. de 2026, 07:42:09 BRT"
9,Searched for,grande é o senhor,https://www.youtube.com/results?search_query=g...,"4 de fev. de 2026, 07:41:57 BRT"
10,Searched for,du.du.yt,https://www.youtube.com/results?search_query=d...,"2 de fev. de 2026, 22:09:19 BRT"
11,Watched,AD71,https://www.youtube.com/watch?v=5IVzOEN6Jpw,"Watched at 16:26 31 de jan. de 2026, 16:26:18 BRT"
12,Searched for,percy jackson cast interview,https://www.youtube.com/results?search_query=p...,"31 de jan. de 2026, 16:26:11 BRT"
13,Watched,Mycon | Como todo consórcio deveria ser (16x9),https://www.youtube.com/watch?v=EPuSc-G3v9A,"Watched at 16:16 31 de jan. de 2026, 16:16:46 BRT"
14,Watched,16x9-Local-Adobe-Progression-PurpleSkatePR+AE,https://www.youtube.com/watch?v=1ETugS912Tg,"Watched at 16:05 31 de jan. de 2026, 16:05:03 BRT"
15,Watched,Cruzeiro do Sul Virtual. Escolha ter Estrela!,https://www.youtube.com/watch?v=o4KipYz89XU,"Watched at 16:04 31 de jan. de 2026, 16:04:38 BRT"
16,Watched,ClickUp Super Agents,https://www.youtube.com/watch?v=FAWWbT7weMs,"Watched at 15:54 31 de jan. de 2026, 15:54:00 BRT"
17,Searched for,bruna marquezine falando ingles,https://www.youtube.com/results?search_query=b...,"31 de jan. de 2026, 15:53:59 BRT"
18,Watched,Explore mundos infinitos,https://www.youtube.com/watch?v=jHnjaaw4JF8,"Watched at 15:53 31 de jan. de 2026, 15:53:37 BRT"
19,Searched for,makeup in english,https://www.youtube.com/results?search_query=m...,"31 de jan. de 2026, 15:50:41 BRT"

Arquivo: histórico-de-visualização.html

--- dtypes antes de convert_dtypes() ---

tipo      object
titulo    object
url       object
data      object
dtype: object

--- dtypes após convert_dtypes() ---

tipo      string[python]
titulo    string[python]
url       string[python]
data      string[python]
dtype: object

📊 Dados (primeiras 20 linhas):

,tipo,titulo,url,data
0,Watched,Deseable - Brunão Morada + Marcos Brunet // So...,https://www.youtube.com/watch?v=9jPJfWqT-So,"Som do Reino 7 de fev. de 2026, 12:36:56 BRT"
1,Watched,Mycon | Como todo consórcio deveria ser (16x9),https://www.youtube.com/watch?v=EPuSc-G3v9A,"Watched at 12:34 7 de fev. de 2026, 12:34:54 BRT"
2,Watched,Cristo Jesus (Ao Vivo) - fhop music & Paulo e ...,https://www.youtube.com/watch?v=Ln46Dfn3QRU,"Fhop Music 7 de fev. de 2026, 12:33:00 BRT"
3,Watched,Jornada Python - ADV LPY25 04h sem data Newton,https://www.youtube.com/watch?v=r4dbQy7IHE8,"Watched at 12:31 7 de fev. de 2026, 12:31:43 BRT"
4,Watched,CAGE0230.Google.PWA.Contentformance_3mil.Calcu...,https://www.youtube.com/watch?v=n1arSFa2gds,"Watched at 11:35 7 de fev. de 2026, 11:35:21 BRT"
5,Watched,Linha Can-Am 2026: Defender,https://www.youtube.com/watch?v=ByQeHi42Upw,"Watched at 11:29 7 de fev. de 2026, 11:29:42 BRT"
6,Watched,"Grande é o Senhor (Ao Vivo) - Altomonte, Davi...",https://www.youtube.com/watch?v=l-2LUSxCaRo,"Altomonte Music 7 de fev. de 2026, 11:18:31 BRT"
7,Watched,Easy Because ClickUp (PT-BR),https://www.youtube.com/watch?v=cWrNNL6Fje4,"Watched at 11:18 7 de fev. de 2026, 11:18:23 BRT"
8,Watched,Grande é o Senhor - Davi Silva,https://www.youtube.com/watch?v=kxnb-gwo2rk,"Welington Luis 7 de fev. de 2026, 11:16:16 BRT"
9,Watched,Grande é o Senhor - Davi Silva,https://www.youtube.com/watch?v=Ee4JPYNvfaE,"Luciane Melo 7 de fev. de 2026, 11:15:45 BRT"
10,Watched,Incensário (Conferência JesusCopy 24’) | Laura...,https://www.youtube.com/watch?v=30VagMEospM,"Laura Souguellis 7 de fev. de 2026, 10:58:15 BRT"
11,Watched,Firmado na Rocha (Yahweh) (Clipe Oficial) - Al...,https://www.youtube.com/watch?v=_AFJSI4fJHs,"Som do Reino 7 de fev. de 2026, 10:58:14 BRT"
12,Watched,Ao Que Está Assentado Sobre o Trono + Nada Vai...,https://www.youtube.com/watch?v=kHKVFxyTjsE,"Altomonte Music 4 de fev. de 2026, 07:50:54 BRT"
13,Watched,"Grande é o Senhor (Ao Vivo) - Altomonte, Davi...",https://www.youtube.com/watch?v=l-2LUSxCaRo,"Altomonte Music 4 de fev. de 2026, 07:42:47 BRT"
14,Watched,Easy Because ClickUp (PT-BR),https://www.youtube.com/watch?v=cWrNNL6Fje4,"Watched at 07:42 4 de fev. de 2026, 07:42:09 BRT"
15,Watched,ESCOLA VOCACIONADA DE TECNOLOGIA,https://www.youtube.com/watch?v=5g8sz6gzuQo,"Instituto J&F 3 de fev. de 2026, 23:56:35 BRT"
16,Watched,Percy Jackson Cast Spill Their Secrets In 'The...,https://www.youtube.com/watch?v=hlzTfuFrdKk,"Capital Buzz 31 de jan. de 2026, 16:26:43 BRT"
17,Watched,AD71,https://www.youtube.com/watch?v=5IVzOEN6Jpw,"Watched at 16:26 31 de jan. de 2026, 16:26:18 BRT"
18,Watched,"Wagner Moura Gained 40 Pounds for Narcos, Shar...",https://www.youtube.com/watch?v=JalCx1yB354,Late Night with Seth Meyers 31 de jan. de 2026...
19,Watched,Mycon | Como todo consórcio deveria ser (16x9),https://www.youtube.com/watch?v=EPuSc-G3v9A,"Watched at 16:16 31 de jan. de 2026, 16:16:46 BRT"

<div style="border: 2px solid #c77dff; padding: 18px; border-radius: 12px; background-color: #f8f0;">  

<h2 style="color:#7b2cbf;">📜 Histórico do YouTube — Arquivos HTML</h2>

<p>
Diferente dos outros arquivos em CSV, o YouTube também exporta parte dos dados do usuário em <b>formato HTML</b>, representando o <b>histórico de atividades</b> realizadas na plataforma.
</p>

<p>
Esses arquivos revelam o <b>comportamento do usuário</b>: o que foi pesquisado e o que foi assistido, incluindo datas, canais e links acessados.
</p>

<hr style="border-color:#c77dff;">

<h3 style="color:#9d4edd;">🔍 histórico de pesquisa.html</h3>

| Coluna | Tipo | Explicação |
|--------|------|------------|
| tipo | object (str) | Indica o tipo de ação realizada (ex: pesquisa feita na barra do YouTube). |
| titulo | object (str) | Texto que foi pesquisado pelo usuário. |
| url | object (str) | Link relacionado ao resultado da pesquisa ou ao conteúdo acessado a partir dela. |
| data | object (str) | Data e hora exata em que a pesquisa foi realizada. |

<p>Esse arquivo mostra exatamente <b>o que o usuário digitou</b> na busca do YouTube ao longo do tempo.</p>

---

<h3 style="color:#9d4edd;">👁️ histórico-de-visualização.html</h3>

| Coluna | Tipo | Explicação |
|--------|------|------------|
| tipo | object (str) | Tipo de ação registrada (visualização de vídeo). |
| titulo | object (str) | Título do vídeo assistido. |
| url | object (str) | Link do canal ou do vídeo assistido. |
| data | object (str) | Data e hora exata em que o vídeo foi assistido, incluindo o fuso horário. |

<p>
Esse arquivo representa um <b>diário completo de consumo de conteúdo</b>, mostrando:
</p>

<ul>
<li>Quais vídeos foram assistidos</li>
<li>Quais canais foram visitados</li>
<li>Em quais dias e horários isso aconteceu</li>
</ul>

<hr style="border-color:#c77dff;">

<p>
Esses dados evidenciam que o YouTube mantém um <b>histórico comportamental detalhado</b> do usuário, permitindo reconstruir seus interesses, rotinas e padrões de consumo ao longo do tempo.
</p>

</div>

In [228]:
def ler_e_exibir_csvs_inscricoes():
    # caminho base usando mesmo padrão que funciona acima
    base_dir = Path("../../Takeout/YouTube e YouTube Music/inscrições")
    
    # pega todos os csv da pasta
    arquivos_csv = list(base_dir.glob("*.csv"))
    
    print(f"Total de arquivos CSV encontrados: {len(arquivos_csv)}\n")
    
    for arquivo in arquivos_csv:
        print(f"\nArquivo: {arquivo.name}")
        
        df = pd.read_csv(arquivo)

        print("\n--- dtypes antes de convert_dtypes() ---")
        display(df.dtypes)

        df = df.convert_dtypes()

        print("\n--- dtypes após convert_dtypes() ---")
        display(df.dtypes)

        print("\n--- Visualização dos dados (primeiras linhas) ---")
        display(df.head())

In [229]:
ler_e_exibir_csvs_inscricoes()

Total de arquivos CSV encontrados: 1


Arquivo: inscrições.csv

--- dtypes antes de convert_dtypes() ---

ID do canal        object
URL do canal       object
Título do canal    object
dtype: object

--- dtypes após convert_dtypes() ---

ID do canal        string[python]
URL do canal       string[python]
Título do canal    string[python]
dtype: object

--- Visualização dos dados (primeiras linhas) ---

,ID do canal,URL do canal,Título do canal
0,UCC_4Qpl1-Kysd-9hRTsoX8w,http://www.youtube.com/channel/UCC_4Qpl1-Kysd-...,WoMakersCode
1,UCGnsRwFS8Xm13lMAeouzT9g,http://www.youtube.com/channel/UCGnsRwFS8Xm13l...,Allie Sherlock
2,UCP_lo1MFyx5IXDeD9s_6nUw,http://www.youtube.com/channel/UCP_lo1MFyx5IXD...,Meta Developers
3,UCbwRqQqZh1ycZ_cZw3rjOLA,http://www.youtube.com/channel/UCbwRqQqZh1ycZ_...,Calebe Cravo
4,UCePyJZBjplMkrMp0kW-HxFg,http://www.youtube.com/channel/UCePyJZBjplMkrM...,The Dream School

<div style="border: 2px solid #c77dff; padding: 18px; border-radius: 12px; background-color: #f8f0;">  

<h2 style="color:#7b2cbf;">🔔 inscrições.csv — Explicação das Colunas</h2>

<p>
Este arquivo registra todos os <b>canais nos quais o usuário está inscrito</b>.  
Ele evidencia que o YouTube mantém um mapeamento completo dos <b>interesses do usuário</b> com base nas inscrições realizadas.
</p>

<hr style="border-color:#c77dff;">

<h3 style="color:#9d4edd;">📋 inscrições.csv</h3>

| Coluna | Tipo | Explicação |
|--------|------|------------|
| ID do canal | object (str) | Identificador único de cada canal no YouTube. Permite relacionar o canal dentro da base de dados da plataforma. |
| URL do canal | object (str) | Endereço direto para a página do canal no YouTube. |
| Título do canal | object (str) | Nome público do canal no qual o usuário está inscrito. |

<hr style="border-color:#c77dff;">

<p>
A partir dessas informações, é possível identificar claramente:
</p>

<ul>
<li>Quais temas despertam o interesse do usuário</li>
<li>Quais criadores de conteúdo ele acompanha</li>
<li>Quais áreas de conhecimento fazem parte da sua rotina de consumo</li>
</ul>

<p>
Isso demonstra que as inscrições funcionam como um <b>indicador direto de preferências pessoais e acadêmicas</b> do usuário dentro da plataforma.
</p>

</div>

In [230]:
def ler_e_exibir_csvs_metadados_do_video():
    # caminho base usando mesmo padrão que funciona acima
    base_dir = Path("../../Takeout/YouTube e YouTube Music/metadados do vídeo")
    
    # pega todos os csv da pasta
    arquivos_csv = list(base_dir.glob("*.csv"))
    
    print(f"Total de arquivos CSV encontrados: {len(arquivos_csv)}\n")
    
    for arquivo in arquivos_csv:
        print(f"\nArquivo: {arquivo.name}")
        
        df = pd.read_csv(arquivo)

        print("\n--- dtypes antes de convert_dtypes() ---")
        display(df.dtypes)

        df = df.convert_dtypes()

        print("\n--- dtypes após convert_dtypes() ---")
        display(df.dtypes)

        print("\n--- Visualização dos dados (primeiras linhas) ---")
        display(df.head())

In [231]:
ler_e_exibir_csvs_metadados_do_video()

Total de arquivos CSV encontrados: 0

<div style="border: 2px solid #c77dff; padding: 18px; border-radius: 12px; background-color: #f8f0;">  

<h2 style="color:#7b2cbf;">🎬 Metadados dos Vídeos — Arquivos CSV</h2>

<p>
Esses três arquivos mostram como o YouTube armazena um <b>conjunto extremamente detalhado de metadados</b> sobre cada vídeo publicado no canal.
Eles registram desde <b>informações geográficas</b> até <b>textos, duração, estado e datas</b> relacionadas aos vídeos.
</p>

<hr style="border-color:#c77dff;">

<h3 style="color:#9d4edd;">📍 gravações de vídeo.csv</h3>

| Coluna | Tipo | Explicação |
|--------|------|------------|
| ID do vídeo | object (str) | Identificador único do vídeo dentro do YouTube. |
| Altitude de gravação do vídeo | int64 | Altitude geográfica associada ao local de gravação do vídeo. |
| Latitude da gravação do vídeo | int64 | Coordenada de latitude do local onde o vídeo foi gravado. |
| Longitude da gravação do vídeo | int64 | Coordenada de longitude do local onde o vídeo foi gravado. |

<p>Mostra que o YouTube pode armazenar <b>informações de localização física</b> associadas aos vídeos.</p>

---

<h3 style="color:#9d4edd;">📝 textos de vídeo.csv</h3>

| Coluna | Tipo | Explicação |
|--------|------|------------|
| ID do vídeo | object (str) | Identificador único do vídeo. |
| Carimbo de data/hora da criação do texto do vídeo | object (str) | Momento em que o título e a descrição foram criados. |
| Segmentos 1 do texto de descrição do vídeo | object (str) | Conteúdo textual da descrição do vídeo. |
| Segmentos 1 do texto do título do vídeo | object (str) | Conteúdo textual do título do vídeo. |
| Carimbo de data/hora da atualização do texto do vídeo | object (str) | Momento da última alteração no título ou descrição. |

<p>Esse arquivo registra o <b>histórico textual</b> do vídeo, incluindo criação e edições.</p>

---

<h3 style="color:#9d4edd;">📊 vídeos.csv</h3>

| Coluna | Tipo | Explicação |
|--------|------|------------|
| ID do vídeo | object (str) | Identificador único do vídeo. |
| Duração aproximada (ms) | int64 | Tempo total do vídeo em milissegundos. |
| Categoria do vídeo | object (str) | Categoria definida pelo YouTube (ex: Pessoas, Educação, Entretenimento). |
| Descrição do vídeo (original) | object (str) | Texto original da descrição do vídeo no momento da publicação. |
| ID do canal | object (str) | Identificador do canal que publicou o vídeo. |
| Título do vídeo (original) | object (str) | Título original do vídeo. |
| Privacidade | object (str) | Define se o vídeo é público, privado ou não listado. |
| Estado do vídeo | object (str) | Situação do processamento do vídeo na plataforma. |
| Carimbo de data/hora de criação do vídeo | object (str) | Momento exato do upload do vídeo. |
| Carimbo de data/hora de publicação do vídeo | object (str) | Momento em que o vídeo se tornou visível ao público. |

<hr style="border-color:#c77dff;">

<p>
Esses três arquivos, juntos, permitem reconstruir completamente:
</p>

<ul>
<li>Quando o vídeo foi criado e publicado</li>
<li>Qual era seu título e descrição originais</li>
<li>Se houve edições nesses textos</li>
<li>Qual a duração e categoria do vídeo</li>
<li>Possível localização geográfica da gravação</li>
</ul>

<p>
Isso evidencia o nível de detalhamento dos <b>metadados armazenados</b> pelo YouTube sobre cada conteúdo publicado.
</p>

</div>

In [232]:
def ler_e_exibir_csvs_music ():
    # caminho base usando mesmo padrão que funciona acima
    base_dir = Path("../../Takeout/YouTube e YouTube Music/music (library and uploads)")
    
    # pega todos os csv da pasta
    arquivos_csv = list(base_dir.glob("*.csv"))
    
    print(f"Total de arquivos CSV encontrados: {len(arquivos_csv)}\n")
    
    for arquivo in arquivos_csv:
        print(f"\nArquivo: {arquivo.name}")
        
        df = pd.read_csv(arquivo)

        print("\n--- dtypes antes de convert_dtypes() ---")
        display(df.dtypes)

        df = df.convert_dtypes()

        print("\n--- dtypes após convert_dtypes() ---")
        display(df.dtypes)

        print("\n--- Visualização dos dados (primeiras linhas) ---")
        display(df.head())

In [233]:
ler_e_exibir_csvs_music()

Total de arquivos CSV encontrados: 0

<div style="border: 2px solid #c77dff; padding: 18px; border-radius: 12px; background-color: #f8f0;">  

<h2 style="color:#7b2cbf;">🎵 music library songs.csv — Explicação das Colunas</h2>

<p>
Este arquivo registra as músicas associadas à biblioteca do YouTube/YouTube Music do usuário.
Ele mostra que a plataforma mantém um <b>catálogo detalhado das músicas consumidas</b>, incluindo título, álbum e todos os artistas envolvidos.
</p>

<hr style="border-color:#c77dff;">

<h3 style="color:#9d4edd;">📋 music library songs.csv</h3>

| Coluna | Tipo | Explicação |
|--------|------|------------|
| ID do vídeo | object (str) | Identificador único do vídeo/música dentro do YouTube. |
| Song Title | object (str) | Nome da música. |
| Album Title | object (str) | Nome do álbum ao qual a música pertence. |
| Artist Name 1 | object (str) | Primeiro artista associado à música (principal). |
| Artist Name 2 | object (str) | Segundo artista participante da música (se houver). |
| Artist Name 3 | object (str) | Terceiro artista participante da música (se houver). |
| Artist Name 4 | object (str) | Quarto artista participante da música (se houver). |
| Artist Name 5 | object (str) | Quinto artista participante da música (se houver). |
| Artist Name 6 | object (str) | Sexto artista participante da música (se houver). |
| Artist Name 7 | object (str) | Sétimo artista participante da música (se houver). |
| Artist Name 8 | object (str) | Oitavo artista participante da música (se houver). |
| Artist Name 9 | object (str) | Nono artista participante da música (se houver). |
| Artist Name 10 | object (str) | Décimo artista participante da música (se houver). |

<hr style="border-color:#c77dff;">

<p>
Esse formato mostra que o YouTube armazena a <b>estrutura completa de autoria musical</b>, permitindo identificar colaborações entre vários artistas em uma mesma faixa.
</p>

<p>
A partir dessas informações, é possível reconstruir os <b>hábitos musicais e preferências do usuário</b> dentro da plataforma.
</p>

</div>

In [234]:
def ler_e_exibir_csvs_playlists():
    # caminho base usando mesmo padrão que funciona acima
    base_dir = Path("../../Takeout/YouTube e YouTube Music/playlists")
    
    # pega todos os csv da pasta
    arquivos_csv = list(base_dir.glob("*.csv"))
    
    print(f"Total de arquivos CSV encontrados: {len(arquivos_csv)}\n")
    
    for arquivo in arquivos_csv:
        print(f"\nArquivo: {arquivo.name}")
        
        df = pd.read_csv(arquivo)

        print("\n--- dtypes antes de convert_dtypes() ---")
        display(df.dtypes)

        df = df.convert_dtypes()

        print("\n--- dtypes após convert_dtypes() ---")
        display(df.dtypes)

        print("\n--- Visualização dos dados (primeiras linhas) ---")
        display(df.head())

In [235]:
ler_e_exibir_csvs_playlists()

Total de arquivos CSV encontrados: 2


Arquivo: playlists.csv

--- dtypes antes de convert_dtypes() ---

Código da playlist                                 object
Adicionar novos vídeos ao topo                     object
Título da playlist (original)                      object
Idioma do título da playlist (original)            object
Carimbo de data/hora da criação da playlist        object
Carimbo de data/hora da atualização da playlist    object
Ordem dos vídeos da playlist                       object
Visibilidade da playlist                           object
dtype: object

--- dtypes após convert_dtypes() ---

Código da playlist                                 string[python]
Adicionar novos vídeos ao topo                     string[python]
Título da playlist (original)                      string[python]
Idioma do título da playlist (original)            string[python]
Carimbo de data/hora da criação da playlist        string[python]
Carimbo de data/hora da atualização da playlist    string[python]
Ordem dos vídeos da playlist                       string[python]
Visibilidade da playlist                           string[python]
dtype: object

--- Visualização dos dados (primeiras linhas) ---

,Código da playlist,Adicionar novos vídeos ao topo,Título da playlist (original),Idioma do título da playlist (original),Carimbo de data/hora da criação da playlist,Carimbo de data/hora da atualização da playlist,Ordem dos vídeos da playlist,Visibilidade da playlist
0,PL_e9Qn9J0FwS1xD_tUr4G2fm1L4kLTfk-,Verdadeiro,Watch later,en_US,2023-10-31T22:02:48+00:00,2023-10-31T22:02:48+00:00,Manual,Privado

Arquivo: Vídeos da playlist Watch later.csv

--- dtypes antes de convert_dtypes() ---

ID do vídeo                                             object
Carimbo de data/hora da criação do vídeo da playlist    object
dtype: object

--- dtypes após convert_dtypes() ---

ID do vídeo                                             string[python]
Carimbo de data/hora da criação do vídeo da playlist    string[python]
dtype: object

--- Visualização dos dados (primeiras linhas) ---

   ID do vídeo Carimbo de data/hora da criação do vídeo da playlist
0  RqfUIh7L1hM                          2023-10-31T22:02:48+00:00

<div style="border: 2px solid #c77dff; padding: 18px; border-radius: 12px; background-color: #f8f0;">  

<h2 style="color:#7b2cbf;"> 📚 Playlists — Estrutura e Vídeos</h2>

<p>
Esses arquivos mostram como o YouTube armazena a <b>estrutura completa das playlists</b> do usuário, incluindo
configurações, organização, datas e todos os vídeos adicionados em cada lista.
</p>

<hr style="border-color:#c77dff;">

<h3 style="color:#9d4edd;"> 📋 playlists.csv (metadados das playlists)</h3>

| Coluna | Tipo | Explicação |
|--------|------|------------|
| Código da playlist | object (str) | Identificador único da playlist dentro do YouTube. |
| Adicionar novos vídeos ao topo | object (str) | Define se novos vídeos entram no início da lista automaticamente. |
| Título da playlist (original) | object (str) | Nome original da playlist criado pelo usuário. |
| Idioma do título da playlist (original) | object (str) | Idioma associado ao título da playlist. |
| Carimbo de data/hora da criação da playlist | object (str) | Momento exato em que a playlist foi criada. |
| Carimbo de data/hora da atualização da playlist | object (str) | Última vez que a playlist foi modificada. |
| Ordem dos vídeos da playlist | object (str) | Define se a ordem é manual ou automática. |
| Visibilidade da playlist | object (str) | Indica se a playlist é pública, privada ou não listada. |

---

<h3 style="color:#9d4edd;"> 🎬 Vídeos da playlist &lt;nome&gt;.csv</h3>

<p>Cada playlist possui um arquivo próprio listando os vídeos que fazem parte dela.</p>

| Coluna | Tipo | Explicação |
|--------|------|------------| 
| ID do vídeo | object (str) | Identificador único do vídeo adicionado à playlist. |
| Carimbo de data/hora da criação do vídeo da playlist | object (str) | Momento exato em que o vídeo foi adicionado à playlist. |

<hr style="border-color:#c77dff;">

<p>
Com esses arquivos é possível reconstruir completamente:
</p>

<ul>
<li>Quais playlists o usuário criou</li>
<li>Como elas estão organizadas</li>
<li>Quando foram criadas e modificadas</li>
<li>Quais vídeos fazem parte de cada uma</li>
<li>Em que momento cada vídeo foi adicionado</li>
</ul>

<p>
Isso revela que o YouTube mantém não apenas os vídeos assistidos, mas também a <b>forma como o usuário organiza o conteúdo</b> dentro da plataforma.
</p>

</div>